### ISSUE TITLE
Prevents tracks from playing on bandcamp.com

### ISSUE THREAD

**Issue by giogziro95** [zpacman/Blockzilla#4]
### Issue

A filter in this list is preventing tracks from playing on _bandcamp.com_ sites.

- Filter: `/track/*$third-party` ([line 647](https://github.com/zpacman/Blockzilla/blob/master/Blockzilla.txt#L647))
- Affected page: _http://godisanastronaut.com/album/all-is-violent-all-is-bright_ (as well as other websites that are powered by _bandcamp.com_)
- Blocked resource: <pre>`https://p4.bcbits.com/download/track/71c373d167dd4eb8d33d50c5796cd2b4/mp3-128/1247672582?fsig=68d4cfd9e5f45320e4bb3748d400e4cf&id=1247672582&stream=1&ts=1492430400.0&token=1492430460_0ccead4f89cd23d0fb73e93bf0e0b2cba3e51b6b`</pre>

The issue is because, in this case, the word _track_ in the URL refers to a music track, not a web tracker.

### Solution

Add the following exception rule to the list:

```
@@||bcbits.com/download/track/*$third-party
```

**Note:** There is already `@@/track/*$media,domain=bandcamp.com` (on the [line 941](https://github.com/zpacman/Blockzilla/blob/master/Blockzilla.txt#L941)), but this doesn't do anything because the _media_ option doesn't match for some reason. Also, adding _domain=bandcamp.com_ prevents it from applying to sites that use a custom domain (such as the one provided above).

**Comment by zpacman** [comment]
@giogziro95 Thank you for reporting the issue! The issue is now fixed, please update the list in Adblock's preferences to see the [fix.](https://github.com/zpacman/Blockzilla/commit/86f1066dec213f43d7d8a07db60a6a61bc170602)

**Comment by giogziro95** [comment]
You're welcome, but it didn't fix it for me. :)

The version is C74, but it's still blocked by the list.

![Screenshot](https://cloud.githubusercontent.com/assets/2781117/25097184/81314ba0-23b4-11e7-94b7-17e7edf79aa3.png)

Did it fix for you?

I can confirm that `@@||bcbits.com/download/track/*$third-party` works.

**Comment by zpacman** [comment]
Seems like the whitelist works in Firefox but not in Chrome. [Fixed](https://github.com/zpacman/Blockzilla/commit/b21ea9e391b726201072f6431f20fa50ba866259) for Chrome.

**Comment by giogziro95** [comment]
I have one question if you don't mind it: Isn't two hours of expiration time a little too small? The majority of lists use at least a day. Any particular reason behind it?

**Comment by zpacman** [comment]
In case of there being a critical false positive, when I apply a fix for it then the short expiration time can ensure that the users of the list are automatically updated with the fix as quick as possible.  Filter list subscriptions with a larger user base choose a longer expiration time to avoid excess load on their servers.

**Comment by giogziro95** [comment]
> Filter list subscriptions with a larger user base choose a longer expiration time to avoid excess load on their servers.

Uh-oh. OK, got it now.

**Comment by giogziro95** [comment]
It should as well have something to do with the list sizes. Of course, large lists can become a client-side problem too since is uses significant traffic while downloading.

**Comment by zpacman** [comment]
> large lists can become a client-side issue as well since they use significant traffic while downloading.

Yes, that would be a factor for lists with a more frequent update interval that have a much larger size than what Blockzilla has. 

Also, it could really only be an issue if the user had multiple large subscription lists enabled which is not recommended anyway. _"It is important to note that you should not add too many filterlists to Adblock Plus. This will slow down the adblocker, therefore, your browsing. As a rule of thumb, it is highly recommended to not use overlapping filterlists."_ - https://adblockplus.org/en/getting_started
